### ISSUE TITLE
Observation space

### ISSUE THREAD

**Issue by bobsaget4lyfe** [nicomon24/Sneks#1]
Hi there,

For observation space you have declared it as a (16,16,3) shape but all observations returns are shape(16,16).

Does this mean that observations are not returned as pixel observations?

**Comment by nicomon24** [comment]
Hi @bobsaget4lyfe, you are right! The cause for this is that I'm still experimenting on how to better represent observation space:
- (16,16) matrix representing block id
- (16,16,3) RGB matrix
I will fix the inconsistency shortly, probably I will create an option in the environment definition to declare the observation type (raw vs. rgb)
